### ISSUE TITLE
Do not read from memory

### ISSUE THREAD

**Issue by gr0uch** [fortunejs/fortune-indexeddb#2]
It should use disk at all times. The reasoning is that shared memory is hard to coordinate and it's much more reliable to just read from disk.

The downside of this approach is that IndexedDB does not provide any querying, so any query options would have to read entire collections from disk. ID lookups should be fine though.

**Comment by darmie** [comment]
I used this adapter in Genie graphql, but Query is not working. Is this why?

**Comment by gr0uch** [comment]
No it's probably a bug. Do you have a stacktrace?

**Comment by darmie** [comment]
Sorry it's my fault. 

Memory can't work from a service worker. So it could not read the data stored in indexeddb. I looked at your implementation and saw that you are not reading from indexeddb

**Comment by gr0uch** [comment]
Ok. Is there any reason why you are using a service worker? How this adapter works is basically like the memory adapter, but it will also persist changes via a web worker using IndexedDB so that the writes don't block the main thread.

**Comment by darmie** [comment]
Using Genie graphql with this plugin was blocking UI thread on the browser. Indexeddb inserts for over 1k data was blocking UI thread. That's why I moved the code inside a service worker

**Comment by gr0uch** [comment]
Hmm. The performance bottleneck here is actually the IPC between main thread and worker, since it has to serialize all that data. There's no more efficient way to do this without sharing memory.

**Comment by gr0uch** [comment]
Done https://github.com/fortunejs/fortune-indexeddb/commit/7ecc838ea1ff12b20b3e9ce407dd51aee7697b1a
