### ISSUE TITLE
Issue with update not saving to IndexedDB

### ISSUE THREAD

**Issue by acoreyj** [fortunejs/fortune-indexeddb#3]
I'm passing 	settings: { enforceLinks: true } on creating fortune but it doesn't seem referential integrity is working for this adapter.

Adding/updating a field is not updating its inverse

**Comment by acoreyj** [comment]
Looked at it a little more and the update request is getting to the indexeddb adapter but it doesn't seem to doing the actual update

**Comment by acoreyj** [comment]
The link update gets stored in memory (so doing a find without reloading will show the inverse link) but not in the DB. Refreshing the page loses the inverse link.
Maybe this is just a problem with the update functionality?

**Comment by acoreyj** [comment]
In the adapter update method the records are being sent to the web worker without applying any updates.

**Comment by acoreyj** [comment]
@daliwali  Would it be as simple as  running the records through the MemoryAdapter update before sending to the web worker?

**Comment by gr0uch** [comment]
The fact that it even updates in memory means that nothing went wrong, the worker thread completed the IndexedDB operation without error.

The automated unit tests pass, this adapter should be working as expected.

Is it possible that you are trying to make multiple updates in different requests simultaneously? This adapter doesn't handle contention at all.

**Comment by acoreyj** [comment]
Thanks for responding.

Yea the worker thread completes without issue but the record sent to the worker thread does not contain the updates. I imagine the tests pass because they are retrieving from memory.

If you look at the code the only time the updates object is used before sending to the worker is to lookup existing objects based on ID.

Here is the code in question, maybe I'm missing something but I'm not sure how the updates would be getting to the IndexedDB. My thought was instead of doing the loop to get the records as they exist should the message worker just be passed the result of calling `MemoryAdapter.prototype.update.call(self, type, updates)`?

```js        
       for (i = 0, j = updates.length; i < j; i++) {
          record = db[type][updates[i][primaryKey]]
          if (!record) continue
          records.push(record)
        }

        if (!records.length) return resolve()

        self.worker.addEventListener('message', listener)
        self.worker.postMessage({
          id: id, method: 'update', type: type,
          records: reduce(records, function (hash, record) {
            var data

            record = inputRecord.call(self, type, record)
            data = msgpack.encode(record)
            transfer.push(data.buffer)
            hash[record[primaryKey]] = data

            return hash
          }, {})
        }, transfer)
```

**Comment by gr0uch** [comment]
Oops, there was a problem in how IDs were applied on updates. This has been fixed in https://github.com/fortunejs/fortune-indexeddb/commit/8066afdabf5906d7599953b22102ca06a2994783#diff-644d8ede25bb88427ccf4229d03bba1bR184

I have also added a demo to manually verify that it should work properly now.

A patch version has been published.

**Comment by acoreyj** [comment]
@daliwali 

Thanks for taking a look, unfortunately the change doesn't seem to have fixed the issue with updates.

The demo looks correct because find is returning what is in memory. The memory is correct because the update function does `MemoryAdapter.prototype.update.call(self, type, updates)`. 

This `updates` object is not sent to the IndexedDB though.

If you were to reload and do a find before the delete you will see that the update did not actually get saved to the IndexedDB.

**Comment by gr0uch** [comment]
I am pretty sure that did fix the issue. Before the fix, there was a record
in indexeddb that looked like ‘person__person__id’ due to the update. The
point is that what is in memory now matches what’s in the db, check the
indexeddb tab in developer tools.

**Comment by acoreyj** [comment]
I do see the issue you are describing is fixed but the actual db data doesn't contain the update. So if you refresh demo and write the results before doing a delete you will see the first created record does not have a reference to the second.

```json
{
  "meta": {},
  "payload": {
    "records": [
      {
        "id": 1,
        "name": "A",
        "friends": []
      },
      {
        "id": 2,
        "name": "B",
        "friends": [
          1
        ]
      }
    ],
    "count": 2
  }
}
```

edit: When looking at the update code do you see what I mean by the `updates` object not being used at all?

**Comment by acoreyj** [comment]
@daliwali 

I proposed a fix that hopefully also illustrates the current issue. Downside is that the memoryAdapter will be updated even if something fails with the indexedDB message.  But since the applyUpdate function isn't exported by common I didn't see another simple way of doing this.

**Comment by gr0uch** [comment]
Ah I see what you mean now, ‘applyUpdate’ isn’t called.

**Comment by gr0uch** [comment]
This should do it: https://github.com/fortunejs/fortune-indexeddb/commit/d3409a86e6eea88d0fca22b4d4674b1120ad74d9

I have published patch versions for both this and `fortune`.
