### ISSUE TITLE
Add typescript definitions

### ISSUE THREAD

**Issue by jerrygreen** [fortunejs/fortune-indexeddb#6]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/13215662/75500924-2f5f0180-59f0-11ea-9ce1-1535b73f4864.png">

**Comment by gr0uch** [comment]
Hmm is a definition really needed? I think it shouldn't really be necessary.

**Comment by jerrygreen** [comment]
@daliwali well, it's not needed for functioning, but it's needed to make all the codebase parts were clearly compliant to each other.

That's more like for Typescript fans. You'll probably be such a one too, later ;) And will find out why it's important on practice
